services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - hopshub_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  backend:
    image: jepmoltho/hopshub:backend-v1.2
    build:
      context: ./HopsHub.Api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
      TESTUSER_PASSWORD: ${TESTUSER_PASSWORD}
      SMTP_SERVER: localhost
      SMTP_PORT: 1025
      SENDER_EMAIL: hopshub@dev.com
      SENDER_NAME: "HopsHub DEV Server"
    depends_on:
      - db
volumes:
  hopshub_sql_data:
# Todo: Run dotnet database update from dockerfile (which is a runtime command, so it might be tricky)
# Todo: Include the mailserver setup in yml file
# Todo: Can you setup running docker network for both containers (yaml file, to start DB, Mailserver and Backend in right order)
# Todo: CI/CD pipelines
