// <auto-generated />
using System;
using HopsHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HopsHub.Api.Migrations
{
    [DbContext(typeof(BeerContext))]
    [Migration("20240928095645_ScoreAndDescriptionProperties")]
    partial class ScoreAndDescriptionProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HopsHub.Api.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Alc")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alc = 6.5m,
                            AverageScore = 0m,
                            Description = "",
                            Name = "Sample IPA",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            Alc = 5.0m,
                            AverageScore = 0m,
                            Description = "",
                            Name = "Crispy Lager",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 3,
                            Alc = 4.2m,
                            AverageScore = 0m,
                            Description = "",
                            Name = "Tart Sour",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Alc = 6.5m,
                            AverageScore = 0m,
                            Description = "",
                            Name = "Other IPA",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("HopsHub.Api.Models.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(3, 1)");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BeerId = 1,
                            Comment = "Nice and bitter IPA",
                            Score = 0m
                        },
                        new
                        {
                            Id = 2L,
                            BeerId = 2,
                            Comment = "Heavy and dark Lager",
                            Score = 0m
                        },
                        new
                        {
                            Id = 3L,
                            BeerId = 3,
                            Comment = "So sour it made my eyes squint",
                            Score = 0m
                        });
                });

            modelBuilder.Entity("HopsHub.Api.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pilsner",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 2,
                            Name = "India Pale Ale",
                            ShortName = "IPA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sour",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lager",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 5,
                            Name = "Other",
                            ShortName = ""
                        });
                });

            modelBuilder.Entity("HopsHub.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HopsHub.Api.Models.Beer", b =>
                {
                    b.HasOne("HopsHub.Api.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HopsHub.Api.Models.Rating", b =>
                {
                    b.HasOne("HopsHub.Api.Models.Beer", null)
                        .WithMany("Ratings")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HopsHub.Api.Models.Beer", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
