// <auto-generated />
using HopsHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HopsHub.Api.Migrations
{
    [DbContext(typeof(BeerContext))]
    [Migration("20240927044158_NavigationFromTypeToBeer")]
    partial class NavigationFromTypeToBeer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HopsHub.Api.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Alc")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alc = 6.5m,
                            Name = "Sample IPA",
                            Rating = 0m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            Alc = 5.0m,
                            Name = "Crispy Lager",
                            Rating = 0m,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 3,
                            Alc = 4.2m,
                            Name = "Tart Sour",
                            Rating = 0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Alc = 6.5m,
                            Name = "Other IPA",
                            Rating = 0m,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("HopsHub.Api.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pilsner",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 2,
                            Name = "India Pale Ale",
                            ShortName = "IPA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sour",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lager",
                            ShortName = ""
                        },
                        new
                        {
                            Id = 5,
                            Name = "Other",
                            ShortName = ""
                        });
                });

            modelBuilder.Entity("HopsHub.Api.Models.Beer", b =>
                {
                    b.HasOne("HopsHub.Api.Models.Type", "Type")
                        .WithMany("Beers")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HopsHub.Api.Models.Type", b =>
                {
                    b.Navigation("Beers");
                });
#pragma warning restore 612, 618
        }
    }
}
